# Generated by Django 3.1.7 on 2021-04-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronunciation_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_accent_name', models.TextField(null=True)),
                ('filename', models.TextField()),
                ('pronunciation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pronunciation.pronunciation')),
            ],
        ),
    ]
