# Generated by Django 3.1.7 on 2021-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0002_pronunciation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation_file',
            name='source',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pronunciation_file',
            name='local_accent_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
