# Generated by Django 3.1.7 on 2021-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0003_auto_20210421_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation',
            name='current_pronunciation_file_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
