# Generated by Django 3.1.7 on 2021-04-26 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0004_pronunciation_current_pronunciation_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation_file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
