# Generated by Django 3.1.7 on 2021-04-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0006_pronunciation_file_choosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronunciation',
            name='current_pronunciation_file_id',
        ),
        migrations.RemoveField(
            model_name='pronunciation',
            name='filename',
        ),
    ]
