# Generated by Django 3.1.7 on 2021-04-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0007_auto_20210430_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pronunciation_file',
            old_name='local_accent_name',
            new_name='accent',
        ),
    ]
