# Generated by Django 3.1.7 on 2021-05-25 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0008_auto_20210430_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
